pipeline {
    agent {
        kubernetes {
            defaultContainer "maven"
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: maven:3-openjdk-11
    command:
    - cat
    tty: true
"""
        }
    }
  stages {
    stage('Build') {
      steps {
        sh """
          mvn clean install findbugs:findbugs
        """
      }
    }
    stage('FindBugs Quality Gate'){
      steps{
        recordIssues qualityGates: [[threshold: 5, type: 'TOTAL', unstable: false]], tools: [findBugs()]
      }
    }
  }
}
