pipeline {
  agent {
    kubernetes {}
  }
  stages {
    stage('Checkout') {
      steps {
        dir("${repoUrl1}".tokenize('/').last()){
          checkout([$class: 'GitSCM', branches: [[name: "*/${repoBranch1}"]], userRemoteConfigs: [[url: "${repoUrl1}"]]])
        }
        dir("${repoUrl2}".tokenize('/').last()){
          checkout([$class: 'GitSCM', branches: [[name: "*/${repoBranch2}"]], userRemoteConfigs: [[url: "${repoUrl2}"]]])
        }
      }
    }
    stage('Build') {
      steps {
        sh """
          echo 'building app...'
          ls -R
        """
      }
    }
  }
}
